name: Build and Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
            node-version: '14.x'
      - name: Install Dependencies
        run: cd cicdApp/ && npm install 
      - name: Build
        run: cd cicdApp/ && npm run build:release
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FOLDER: dist

       

